services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  cache.advertisement_campaign_totalstatistic:
    class: TYPO3\CMS\Core\Cache\Backend\SimpleFileBackend
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['advertisement_campaign_totalstatistic']
    
  Slavlee\Advertisement\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
      
  Slavlee\Advertisement\Cache\Backend\FileBackend:
    public: true
    arguments:
      $cache: '@cache.advertisement_campaign_totalstatistic'